services:
  bot:
    container_name: its-meetup-c-sharp-bot
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
      - .env
    environment:
      DATABASE_URI: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    networks:
      - host
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.3-alpine3.20
    container_name: its-meetup-c-sharp-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - host
    volumes:
      - ${POSTGRES_VOLUME:-./.volume}:/var/lib/postgresql/data

networks:
  host:
    driver: bridge
